version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    ports:
      - 54333:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_ADDR: postgres
      KC_DB_DATABASE: keycloak
      KC_DB_USER: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres

    volumes:
      - "./themes/:/opt/keycloak/themes/"
      - "./keycloak-providers:/opt/keycloak/providers"
